# book settings
title: Open Science for Computer Simulation
author: Thomas Monks
#logo: images/logo.png
email: t.m.w.monks@exeter.ac.uk
copyright: "2021"  # Copyright year to be placed in the footer
description: >- # this means to ignore newlines until "baseurl:"
  Learning materials for Open Science for Computer Simulation.


#only build files specified in table of contents file
only_build_toc_files: true

execute:
  execute_notebooks: cache #cache output from .ipynb files for faster build
  timeout: -1 #no time restriction on notebook execution
  
repository:
  url: https://github.com/TomMonks/open-science-for-sim
  branch: main
  
html:
  use_repository_button: true
  use_issues_button: true
  
# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
